# Generated by Django 2.0.2 on 2020-06-01 06:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_auto_20200601_1200'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='img',
            new_name='image',
        ),
    ]
